include:
  - remote: "https://gitlab.com/gemseo/dev/ci-includes/-/raw/main/plugin.yml"

variables:
  TEST_DOCKER_IMAGE: registry.gitlab.com/gemseo/dev/gemseo-petsc/multi-python-miniforge
  PYTEST_NUM_PROCESSES: 1
