include:
  - remote: "https://gitlab.com/gemseo/dev/ci-includes/-/raw/main/plugin.yml"

variables:
  TOX_EXE: tox4

pages:
  stage: publish
  image: $TEST_DOCKER_IMAGE
  variables:
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
    MIKE_BRANCH: docs-site
  cache:
    paths:
      - $PIP_CACHE_DIR
    key:
      files:
        - requirements/doc.txt
      prefix: $TEST_DOCKER_IMAGE
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        MIKE_ARGS: $CI_COMMIT_REF_NAME
    - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TAG
      variables:
        MIKE_ARGS: $CI_COMMIT_TAG latest --update-aliases
  before_script:
    - |
      function config_git_push() {
        # Configure git to be able to make changes and push.
        git config user.email "<>"
        git config user.name "$GITLAB_USER_LOGIN"
        local git_base_url=$(echo "$CI_REPOSITORY_URL" | cut -d\@ -f2)
        git remote set-url origin https://token:$GITLAB_API_AND_PUSH_TOKEN@$git_base_url
      }
  script:
    - $TOX_EXE -e doc --notest
    - . .tox/doc/bin/activate
    # By default gitlab does not fetch all branches.
    - git fetch origin $MIKE_BRANCH --depth=1
    - config_git_push
    - mike deploy --branch $MIKE_BRANCH --push $MIKE_ARGS
    # - mike set-default --branch $MIKE_BRANCH --push $MIKE_ARGS
    - git checkout $MIKE_BRANCH -- public
  artifacts:
    paths:
      - public
